### ISSUE TITLE
开发所需工具不理解

### ISSUE THREAD

**Issue by Destinyhxq** [runforever/py4g#1]
所以编辑器，解释器分别是用来干嘛的，有什么关系呢？
搭建本地的开发环境，是不是可以讲解一下，现在还是只能在浏览器上面编辑。

**Comment by runforever** [comment]
我考虑将搭好的环境效果图加入到书中，可能会搭配视频让读者有更好的理解

**Comment by runforever** [comment]
已经将开发工具章节重排，添加了详细使用编辑器，使用 Terminal，使用书中示例代码的步骤。
